services:
  auto_unlocker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auto_unlocker_1
    restart: unless-stopped
    env_file:
      - ./env/.env
    environment:
      - TZ=Asia/Novosibirsk
      - CONFIG_PATH=/app/config.json
    volumes:
      - ./logs:/app/logs  # Логи на хосте
      - ./env/.env:/app/.env   # .env как bind-mount
      - ./config.json:/app/config.json  # настройки
    healthcheck:
      test: ["CMD", "python", "-c", "import requests"]
      interval: 1m
      timeout: 10s
      retries: 3

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile.telegram_bot
    container_name: telegram_bot_1
    restart: unless-stopped
    env_file:
      - ./env/.env
    environment:
      - TZ=Asia/Novosibirsk
      - CONFIG_PATH=/app/config.json
    depends_on:
      - auto_unlocker
    user: root
    volumes:
      - ./logs:/app/logs  # Логи на хосте
      - ./env/.env:/app/.env   # .env как bind-mount
      - ./config.json:/app/config.json  # настройки
      - /var/run/docker.sock:/var/run/docker.sock
      - ./blocked_chat_ids.json:/app/blocked_chat_ids.json  # файл блокировок

volumes:
  shared_data: 